save_dir: save_results

dataset: "acyclic"
data_file: data_file.json

# GNN_train
train_gnn: True
gnn_epochs: 2000
mlp_hidden: -1
input_dim: 1  # node feature dim
latent_dim: 8 16  # latent dims for the GNN separated by spaces.
gnn_learning_rate: 0.005
gnn_momentum: 0.9
gnn_weight_decay: 5e-4
model_file: test_acyclic.pth

# GNN_explain
max_nodes: 4
max_steps: 30
max_iters: 50
num_classes: 2
node_types: 1
target_class: 1
learning_rate: 0.01
roll_out_alpha: 2
roll_out_penalty: -0.1
reward_stepwise: 0.1
start_from: "existing" # whether start from existing graph or set the graph

#device: -1
#log_file: train.log
