save_dir: save_results
# data_dir: MUTAG/
dataset: "MUTAG"

data_file: data_file.json

# GNN_train
train_gnn: False
gnn_epochs: 2000
mlp_hidden: 32
input_dim: 7  # node feature dim
latent_dim: 32 48 64  # latent dims for the GNN separated by spaces.
gnn_learning_rate: 0.005
gnn_momentum: 0.9
gnn_weight_decay: 5e-4
# adjacency_matrix_file: MUTAG_A.txt
# graph_labels_file: MUTAG_graph_labels.txt
# graph_indicator_file: MUTAG_graph_indicator.txt
# node_labels_file: MUTAG_node_labels.txt
model_file: original_XGNN_MUTAG_ckpt.pth

# GNN_explain
max_nodes: 5
max_steps: 20
max_iters: 5
num_classes: 2
node_types: 7
target_class: 1
learning_rate: 0.0001
roll_out_alpha: 2
roll_out_penalty: -0.1
reward_stepwise: 0.1
start_from: "existing" # whether start from existing graph or set the graph
#start_from: ""

#device: -1
#log_file: train.log
